### ISSUE TITLE
Having issues with ESPhome but not Tasmota... 

### ISSUE THREAD

**Issue by AaronAnz** [mightymos/RF-Bridge-OB38S003#22]
Firstly, awesome work and great write up. I'm new to esp devices realm and it was pretty easy to follow but i'm having a weird issue with esphome. I prefer the look and configuration methods for esphome over tasmota so I really wanna get it to work in favor of Tasmota but im having issues. 

I have a Sonoff RF Bridge R2.2. I successfully flashed the Passthrough firmware you provided flashed to the RF chip and when I flash the ESP chip with Tasmota and configured as you designated and everything works great with this:
```
RfSend 0xA110E0E, 32, 1, 5, 269
RfSend 0xA111E1E, 32, 1, 5, 270
```

but when I flash esphome this wont work to turn to control my device:

```
substitutions:
  name: "sonoff-rf-bridge-r2"
  friendly_name: "Sonoff RF Bridge r2.2"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: Sonoff RF BridgeR2 with ESPHome

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  power_save_mode: NONE
  manual_ip: 
    static_ip: !secret device_ip
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret gateway
  ap:
    ssid: "${friendly_name} Backup AP"
    password: !secret wifi_password

web_server:
  port: 80
  ota: true
  local: true

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG
  hardware_uart: UART1

captive_portal:

api:
  password: !secret api_password


status_led:
  pin: GPIO13

remote_receiver:
  pin:
    number: GPIO3
    mode:
      input: true
      pullup: false
      
  tolerance: 50%
  filter: 4us
  idle: 4ms
  dump: rc_switch

remote_transmitter:
  pin: GPIO1
  carrier_duty_percent: 100%

button:
  - platform: template
    name: "Send RF Code OFF"
    on_press:
      - remote_transmitter.transmit_rc_switch_raw:
          code: "00001010000100010000111000001110" # 0x0xA110E0E padded to 32 bits
          protocol: 1
          repeat: 5
```

Any help would be greatly appreciated!
